[tool.poetry]
name = "python-desafio-dio-sisbanco"
version = "0.1.0"
description = ""
authors = ["fabiocasadossites <contato@casadossites.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
